# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "coverage" ]
  pull_request:
    branches: [ "coverage" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Test # only test a simple pkg.
      run: go test -covermode=atomic -coverprofile=coverage.out -v ./config/... ./metrics/...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unit,integration
        verbose: true

